version: '2'

services:
  app:
    image: ecommerce
    build: .
    container_name: app
    depends_on:
      - db
    profiles:
      - deploy
    ports:
      - '8080:8080'
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ecommerce
    ports:
      - '5433:5432'